services:
  - type: web
    name: arcreate-backend
    runtime: node
    buildCommand: npm install
    startCommand: node src/backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false

  - type: web
    name: arcreate-frontend
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: arcreate-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL